-- Script was generated by Devart Entity Developer, Version 6.2.414.0
-- Script date 22.1.2018. 19:05:56
-- Target Server: SQLite
-- Server Version: 3.7

-- 
-- Creating a table "main".Category 
-- 
CREATE TABLE "main".Category (
   CategoryId INTEGER PRIMARY KEY AUTOINCREMENT,
   Name TEXT NOT NULL,
   CONSTRAINT FK_Category_Category_0 FOREIGN KEY (CategoryId) REFERENCES Category (CategoryId)
);

-- 
-- Creating a table "main".Users 
-- 
CREATE TABLE "main".Users (
   UserId INTEGER PRIMARY KEY AUTOINCREMENT,
   FirstName TEXT NOT NULL,
   LastName TEXT NOT NULL,
   DateHired DATETIME NOT NULL,
   DateFired DATETIME
);

-- 
-- Creating a table "main".Assets 
-- 
CREATE TABLE "main".Assets (
   AssetId INTEGER PRIMARY KEY AUTOINCREMENT,
   IsActive INTEGER NOT NULL,
   DateAcquired DATETIME NOT NULL,
   DateDisposed DATETIME NOT NULL,
   CategoryId INTEGER NOT NULL,
   CONSTRAINT FK_Assets_Category_0 FOREIGN KEY (CategoryId) REFERENCES Category (CategoryId)
);

-- 
-- Creating a table "main".Inventory 
-- 
CREATE TABLE "main".Inventory (
   AssetId INTEGER NOT NULL,
   UserId INTEGER NOT NULL,
   DateFrom DATETIME NOT NULL,
   DateTo DATETIME,
   CONSTRAINT PK_Inventory PRIMARY KEY (AssetId, UserId),
   CONSTRAINT FK_Inventory_Assets_0 FOREIGN KEY (AssetId) REFERENCES Assets (AssetId),
   CONSTRAINT FK_Inventory_Users_1 FOREIGN KEY (UserId) REFERENCES Users (UserId)
);

