//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate Fluent Mapping template.
// Code is generated on: 4.2.2018. 16:43:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using FluentNHibernate.Mapping;
using FluentNHibernate.MappingModel.Collections;

namespace Inventory
{
    /// <summary>
    /// There are no comments for CategoryMap in the schema.
    /// </summary>
    public partial class CategoryMap : ClassMap<Category>
    {
        /// <summary>
        /// There are no comments for CategoryMap constructor in the schema.
        /// </summary>
        public CategoryMap()
        {
              Schema(@"main");
              Table(@"Category");
              LazyLoad();
              Id(x => x.Id)
                .Column("CategoryId")
                .CustomType("Int32")
                .Access.Property()                
                .GeneratedBy.Identity();
              Map(x => x.Name)    
                .Column("Name")
                .CustomType("String")
                .Access.Property()
                .Generated.Never();
              HasMany<Equipment>(x => x.Equipments)
                .Access.Property()
                .AsBag()
                .Cascade.SaveUpdate()
                .LazyLoad()
                // .OptimisticLock.Version() /*bug (or missing feature) in Fluent NHibernate*/
                .Inverse()
                .Generic()
                .KeyColumns.Add("CategoryId", mapping => mapping.Name("CategoryId")
                                                                     .Nullable());
              HasMany<Category>(x => x.ChildCategories)
                .Access.Property()
                .AsBag()
                .Cascade.SaveUpdate()
                .LazyLoad()
                // .OptimisticLock.Version() /*bug (or missing feature) in Fluent NHibernate*/
                .Inverse()
                .Generic()
                .KeyColumns.Add("ParentId", mapping => mapping.Name("ParentId")
                                                                     .Nullable());
              References(x => x.ParentCategory)
                .Class<Category>()
                .Access.Property()
                .Cascade.SaveUpdate()
                .LazyLoad()
                .Columns("ParentId");
              ExtendMapping();
        }

        #region Partial Methods

        partial void ExtendMapping();

        #endregion
    }

}
